num1=eval(input("Etner first number : "))
num2=eval(input("Etner second number : "))
print("Sum = " ,num1+num2)
print("Substraction = ",num1-num2)
print("Multiplication = ",num1*num2)
print("Divide = ",num1/num2)