# Generated by Django 3.0.8 on 2020-07-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('contactno', models.CharField(max_length=15)),
                ('emailaddress', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
